mutation AddNewReview($customerId: UUID!, $producerId: UUID!, $productId: UUID!, $rating: Int!, $reviewText: String!) @auth(level: USER) {
  review_insert(data: {
    customerId: $customerId,
    producerId: $producerId,
    productId: $productId,
    rating: $rating,
    reviewText: $reviewText,
    createdAt_expr: "request.time"
  })
}

query ListProductsByCategory($category: String!) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  products(where: {category: {eq: $category}}) {
    id
    name
    description
    imageUrl
    price
  }
}

mutation UpdateStockQuantity($id: UUID!, $stockQuantity: Int!) @auth(level: USER) {
  product_update(
    key: {id: $id}
    data: {stockQuantity: $stockQuantity}
  )
}

query GetUserReviews($customerId: UUID!) @auth(level: USER) {
  reviews(where: {customerId: {eq: $customerId}}) {
    id
    productId
    rating
    reviewText
    createdAt
  }
}